package com.hjfruit.test.pitaya.entities.production.common;

/**
 * 入库类型
 */
public enum InStockOrderType {
    PRODUCTION_IN_APPLY, RAW_PURCHASE, RAW_RETURN, SEMI_FINISHED_IN_APPLY, DEFECTIVE_IN_APPLY, SUB_PURCHASE, SUB_RETURN, CHECK_IN_APPLY, OTHER_IN_APPLY, TURNOVER_BASKET_RETURN, SALES_RETURN, RETURNED_GOODS_RETURN, SEMI_FINISHED_PRODUCTS_RETURN,
}