package com.hjfruit.test.pitaya.entities.production.common;

/**
 * 出库类型
 */
public enum OutStockOrderType {
    RAW_MATERIAL_ACQUISITION, SUPPLEMENTARY_MATERIAL_ACQUISITION, RETURNED_GOODS_OUT, FINISHED_PRODUCT_ACQUISITION, SEMI_FINISHED_PRODUCT_ACQUISITION, OTHER_ACQUISITION, DAMAGED_ACQUISITION, CHECK_ACQUISITION, DEFECTIVE_SALE, PURCHASE_RETURN, TRANSFER_OUT_APPLY, DAMAGED_RAW_MATERIAL, DAMAGED_SEMI_FINISHED_PRODUCT, DAMAGED_RETURNED_GOODS,
}