spring:
  datasource:
    pitaya:
      jdbc-url: jdbc:postgresql://192.168.0.246:5440/pitaya?useUnicode=true&characterEncoding=utf-8&TimeZone=Asia/Shanghai
      username: pitaya
      password: pitaya
      driver-class-name: org.postgresql.Driver
    peach:
      jdbc-url: jdbc:postgresql://192.168.0.246:5440/peach?currentSchema=wholesale&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&TimeZone=Asia/Shanghai
      username: peach
      password: peach
      driver-class-name: org.postgresql.Driver
    fc-mdm:
      jdbc-url: jdbc:postgresql://192.168.0.239:5441,192.168.0.9:5441/fc_mdm?currentSchema=fc_customer&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&rewriteBatchedStatements=true&TimeZone=Asia/Shanghai
      username: hj
      password: hj
      driver-class-name: org.postgresql.Driver
graphql:
  config:
    server: https://pitaya-test.hjgpscm.com/graphql